name = input("Kar jonno wish? ")
time = input("Kokhon birthday? ")
print()
print("="*30)
print("  HAPPY BIRTHDAY", name.upper(), "👑")
print("  From: Sohom ❤️")
print("  Date:", time)
print("="*30)
print("Sohom bolche: Tui best re!")
